# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PassLock_Locker.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PassLock_Secondary import Ui_Dialog as Storage


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 80, 340, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 130, 141, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(264, 130, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 170, 100, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.setStyleSheet("QLabel {color : red}")

        self.pushButton.clicked.connect(self.toggle_visibility)
        self.pushButton_2.clicked.connect(self.confirm_password)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Locker"))
        self.label.setText(_translate("Dialog", "Enter your password : "))
        self.pushButton.setText(_translate("Dialog", "View / Hide Password"))
        self.pushButton_2.setText(_translate("Dialog", "Confirm"))

        self.lineEdit.setEchoMode(self.lineEdit.Password)

    def confirm_password(self):
        self.label_2.setText("")
        password = self.lineEdit.text()

        if password == "Vishal@229198112":
            self.lineEdit.clear()
            
            dialog = QtWidgets.QDialog()
            dialog.ui = Storage()
            dialog.ui.setupUi(dialog)
            dialog.exec_()
            dialog.show()

        else:
            self.label_2.setText("Incorrect Password !")
            
    def toggle_visibility(self):
        if self.lineEdit.echoMode() == self.lineEdit.Password:
            self.lineEdit.setEchoMode(self.lineEdit.Normal)
        else:
            self.lineEdit.setEchoMode(self.lineEdit.Password)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
