# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interests.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import tabulate


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400,400)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 380, 40))
        self.label.setObjectName("label")       
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(26)
        self.label.setFont(font)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 250, 20))
        self.label_2.setObjectName("label_2")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 250, 20))       
        self.label_3.setObjectName("label_3")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 250, 20))        
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 250, 20))        
        self.label_5.setObjectName("label_5")

        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 250, 20))        
        self.label_6.setObjectName("label_6")

        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(278, 70, 110, 30))        
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Simple")
        self.comboBox.addItem("Compound")

        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(280, 120, 110, 30))        
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("Annually")
        self.comboBox_2.addItem("Half-yearly")
        self.comboBox_2.addItem("Quarterly")
        self.comboBox_2.addItem("Monthly")
        
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(100, 320, 290, 70))        
        self.textBrowser.setObjectName("textBrowser")

        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 320, 80, 30))        
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 360, 80, 30))        
        self.pushButton_2.setObjectName("pushButton_2")

        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(10)

        self.label_2.setFont(font)
        self.label_3.setFont(font)
        self.label_4.setFont(font)
        self.label_5.setFont(font)
        self.label_6.setFont(font)
        self.comboBox.setFont(font)
        self.comboBox_2.setFont(font)
        self.textBrowser.setFont(font)
        self.pushButton.setFont(font)
        self.pushButton_2.setFont(font)

        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(280, 170, 110, 30))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(280, 220, 110, 30))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(280, 270, 110, 30))
        self.lineEdit_3.setObjectName("lineEdit_3")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        self.lineEdit.setFont(font)
        self.lineEdit_2.setFont(font)
        self.lineEdit_3.setFont(font)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Interests Calculator"))
        self.label.setText(_translate("Dialog", "Interests Calculator"))
        self.label_2.setText(_translate("Dialog", "Type of Interests ( Interest Wise ) :"))
        self.label_3.setText(_translate("Dialog", "Type of Interests ( Duration Wise ) :"))
        self.label_4.setText(_translate("Dialog", "Principal Amount of Interest :"))
        self.label_5.setText(_translate("Dialog", "Rate of Interest :"))
        self.label_6.setText(_translate("Dialog", "Duration of Interest (Months) :"))
        self.pushButton.setText(_translate("Dialog", "Calculate"))
        self.pushButton_2.setText(_translate("Dialog", "Reset"))

        self.pushButton.clicked.connect(self.calculate)
        self.pushButton_2.clicked.connect(self.reset)

    def calculate(self):
        interest_type = self.comboBox.currentText()
        duration_type = self.comboBox_2.currentText()
        principal = int(self.lineEdit.text())
        rate = int(self.lineEdit_2.text())
        duration = int(self.lineEdit_3.text())

        if interest_type == "Simple":
            interest = (principal*rate*duration)/1200
            amount = principal + interest

        elif interest_type == "Compound":
            if duration_type == "Annually":
                amount = principal*(((100+rate)/100)**duration/12)
                interest = amount - principal
            if duration_type == "Half-yearly":
                amount = principal*(((200+rate)/200)**duration/6)
                interest = amount - principal
            if duration_type == "Quarterly":
                amount = principal*(((400+rate)/400)**duration/3)
                interest = amount - principal
            if duration_type == "Monthly":
                amount = principal*(((1200+rate)/1200)**duration)
                interest = amount - principal

        interest = round(interest, 2)
        amount = round(amount, 2)

        TEXT = f"Interest Applied : {interest}\n\nTotal Amount : {amount}"

        header = ["Description","Data"]

        data_table = [["",""],["Type of Interest",interest_type],["Duration Type",duration_type],["Principal Amount",principal],["Rate of Interest",f"{rate}%"],["Duration of Interest (Months)",duration],["",""],["Interest Applied",interest],["Total Amount",amount]]
              
        with open("DataSheet.txt", "a") as writer:
            writer.write("Data Sheet :\n\n")
            writer.write(tabulate.tabulate(data_table, headers=header, tablefmt="grid",colalign=("left",)))
            writer.write("\n\n")

        self.textBrowser.setText(TEXT)

    def reset(self):
        self.comboBox.setCurrentText("Simple")
        self.comboBox_2.setCurrentText("Annually")
        self.lineEdit.setText("")
        self.lineEdit_2.setText("")
        self.lineEdit_3.setText("")
        self.textBrowser.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
