number = 0

questions = [
                [number, "Which city is also known as the 'City of joy' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Kolkata"],
                [number, "Which city is also known as the 'City of dreams' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Mumbai"],
                [number, "Which city is also known as the 'Silicon Valley of India' ?", "Kolkata", "Mumbai", "Bangalore", "Delhi", "Bangalore"],
                [number, "Which city is also known as the 'Steel city of India' ?", "Kolkata", "Jamshedpur", "Chennai", "Delhi", "Jamshedpur"],
                [number, "Which city is also known as the 'Rome of the East' ?", "Kolkata", "Mumbai", "Chennai", "Mangalore", "Mangalore"],
                [number, "Which city is also known as the 'Land of knowledge' ?", "Nalanda", "Mumbai", "Chennai", "Delhi", "Nalanda"],
                [number, "Which city is also known as the 'Coal Capital of India' ?", "Kolkata", "Dhanbad", "Chennai", "Delhi", "Dhanbad"],
                [number, "Which city is also known as the 'Cashew Capital of the World' ?", "Kolkata", "Mumbai", "Kolam", "Delhi", "Kolam"],
                [number, "Which city is also known as the 'Oxford of the East' ?", "Kolkata", "Mumbai", "Pune", "Delhi", "Pune"],
                [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                [number, "What is the formula to find the volume of a cone ?", "pi*r*r*h", "r*h*l", "pi*r*r*h/3", "2*r*r*h", "pi*r*r*h/3"]
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
            ]
