# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Translator_Settings_by_VK.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import googletrans
from Translator_by_VK import Ui_MainWindow as Main


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(9, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 381, 100))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 40, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 40, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(70, 30, 141, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 60, 141, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(240, 20, 131, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 60, 131, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 381, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 40, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(240, 30, 40, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox_2)
        self.fontComboBox.setGeometry(QtCore.QRect(80, 30, 141, 22))
        self.fontComboBox.setObjectName("fontComboBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(300, 30, 51, 22))
        self.spinBox.setMinimum(8)
        self.spinBox.setMaximum(28)
        self.spinBox.setProperty("value", 12)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 70, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 70, 131, 21))
        self.pushButton_4.setObjectName("pushButton_4")

        for x in googletrans.LANGUAGES.values():
            self.comboBox.addItem(x.capitalize())
            self.comboBox_2.addItem(x.capitalize())

        self.comboBox.setCurrentText("English")
        self.comboBox_2.setCurrentText("Hindi")
        self.fontComboBox.setCurrentText("Dubai")
        self.spinBox.setValue(18)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Translator Settings"))
        self.label.setText(_translate("Dialog", "Translator Settings"))
        self.groupBox.setTitle(_translate("Dialog", "Language Defaulters :"))
        self.label_2.setText(_translate("Dialog", "From :"))
        self.label_3.setText(_translate("Dialog", "To :"))
        self.pushButton.setText(_translate("Dialog", "Save"))
        self.pushButton_3.setText(_translate("Dialog", "Discard"))
        self.groupBox_2.setTitle(_translate("Dialog", "Font ( Only for the body and the saved content ) :"))
        self.label_4.setText(_translate("Dialog", "Style :"))
        self.label_5.setText(_translate("Dialog", "Size :"))
        self.pushButton_2.setText(_translate("Dialog", "Save"))
        self.pushButton_4.setText(_translate("Dialog", "Discard"))

        self.pushButton.clicked.connect(self.save_changes)
        self.pushButton_2.clicked.connect(self.save_changes)
        self.pushButton_3.clicked.connect(self.reset_changes)
        self.pushButton_4.clicked.connect(self.reset_changes)

    def save_changes(self):
        value_from = self.comboBox.currentText()
        value_to = self.comboBox_2.currentText()
        style = self.fontComboBox.currentText()
        size = self.spinBox.value()
        main = Main()
        font = QtGui.QFont()
        font.setFamily(style)
        font.setPointSize(size)
        main.comboBox.setCurrentText(value_from)
        main.comboBox_2.setCurrentText(value_to)
        main.label.setFont(font)
        main.label_2.setFont(font)
        main.label_3.setFont(font)
        main.label_4.setFont(font)
        main.label_5.setFont(font)
        main.label_6.setFont(font)

    def reset_changes(self):
        main = TbV.Ui_MainWindow()
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        main.comboBox.setCurrentText("English")
        main.comboBox_2.setCurrentText("Hindi")
        main.label.setFont(font)
        main.label_2.setFont(font)
        main.label_3.setFont(font)
        main.label_4.setFont(font)
        main.label_5.setFont(font)
        main.label_6.setFont(font)


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
