# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Notes-2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 201, 70))
        self.groupBox.setObjectName("groupBox")
        self.fontComboBox = QtWidgets.QFontComboBox(self.groupBox)
        self.fontComboBox.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.fontComboBox.setObjectName("fontComboBox")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(239, 60, 131, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox.setGeometry(QtCore.QRect(21, 31, 91, 20))
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(96)
        self.spinBox.setProperty("value", 14)
        self.spinBox.setObjectName("spinBox")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 140, 201, 70))
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 30, 161, 22))
        self.comboBox.setObjectName("comboBox")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 220, 201, 70))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 30, 161, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(240, 140, 141, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(20, 30, 101, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 70, 101, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 110, 101, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fonts"))
        self.label.setText(_translate("Dialog", "Fonts :"))
        self.groupBox.setTitle(_translate("Dialog", "Styles"))
        self.groupBox_2.setTitle(_translate("Dialog", "Sizes"))
        self.groupBox_3.setTitle(_translate("Dialog", "Colors"))
        self.groupBox_4.setTitle(_translate("Dialog", "Backgrounds"))
        self.groupBox_5.setTitle(_translate("Dialog", "Options :"))
        self.pushButton.setText(_translate("Dialog", "Save Changes"))
        self.pushButton_2.setText(_translate("Dialog", "Discard Changes"))
        self.pushButton_3.setText(_translate("Dialog", "Reset Changees"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Dialog = QtWidgets.QDialog()
#     ui = Ui_Dialog()
#     ui.setupUi(Dialog)
#     Dialog.show()
#     sys.exit(app.exec_())
