# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Timer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEventLoop, QTimer


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setFixedSize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 380, 50))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 140, 220))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setGeometry(QtCore.QRect(80, 30, 50, 30))
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setGeometry(QtCore.QRect(80, 80, 50, 30))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_3.setGeometry(QtCore.QRect(80, 130, 50, 30))
        self.spinBox_3.setObjectName("spinBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 100, 23))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(170, 120, 210, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(170, 120, 3, 80))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(380, 120, 3, 80))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(170, 200, 210, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(190, 140, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(170, 80, 210, 30))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 220, 100, 23))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(170, 260, 100, 23))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(290, 220, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(290, 260, 90, 23))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Timer"))
        self.label.setText(_translate("Dialog", "Timer"))
        self.groupBox.setTitle(_translate("Dialog", "Menu :"))
        self.pushButton.setText(_translate("Dialog", "Set Timer"))
        self.label_2.setText(_translate("Dialog", "Hours :"))
        self.label_3.setText(_translate("Dialog", "Minutes :"))
        self.label_4.setText(_translate("Dialog", "Seconds :"))
        self.label_5.setText(_translate("Dialog", "Countdown"))
        self.pushButton_2.setText(_translate("Dialog", "Stop"))
        self.pushButton_3.setText(_translate("Dialog", "Reset"))
        self.pushButton_4.setText(_translate("Dialog", "+1 minute"))
        self.pushButton_5.setText(_translate("Dialog", "Delete"))

        self.pushButton.clicked.connect(self.set_timer)
        self.pushButton_2.clicked.connect(self.pause_timer)
        self.pushButton_3.clicked.connect(self.reset_timer)
        self.pushButton_4.clicked.connect(self.minute_plus)
        self.pushButton_5.clicked.connect(self.delete_all)

        self.pause = True

        self.hours = 0
        self.minutes = 0
        self.seconds = 0

        timer = QTimer(Dialog)
        timer.timeout.connect(self.run_timer)
        timer.start(1000)

    def set_timer(self):
        self.pushButton.setDisabled(True)
        self.pause = False

        self.hours = self.spinBox.value()
        self.minutes = self.spinBox_2.value()
        self.seconds = self.spinBox_3.value()

        self.textBrowser.setText(f"{str(self.hours).zfill(2)}:{str(self.minutes).zfill(2)}:{str(self.seconds).zfill(2)}")

    def run_timer(self):
        if self.pause == True:
            pass

        elif self.pause == False:
            if self.hours == self.minutes == self.seconds == 0:
                self.textBrowser.setText("00:00:00")

            else:
                if self.minutes == self.seconds == 0:
                    self.hours -= 1
                    self.minutes += 59
                    self.seconds += 59

                elif self.seconds == 0:
                    self.minutes -= 1
                    self.seconds += 59

                else:
                    self.seconds -= 1
                    
                self.textBrowser.setText(f"{str(self.hours).zfill(2)}:{str(self.minutes).zfill(2)}:{str(self.seconds).zfill(2)}")

    def pause_timer(self):
        if self.pause == False:
            self.pause = True
            self.pushButton_2.setText("Resume")

        else:
            self.pause = False
            self.pushButton_2.setText("Stop")

    def reset_timer(self):
        if self.pause == False:
            self.pause = True

        else:
            self.pause = False

        self.hours = 0
        self.minutes = 0
        self.seconds = 0

        self.pushButton.setDisabled(False)

        self.textBrowser.setText(f"{str(self.hours).zfill(2)}:{str(self.minutes).zfill(2)}:{str(self.seconds).zfill(2)}")
        self.pushButton_2.setText("Stop")

    def delete_all(self):
        self.reset_timer()

        self.spinBox.setValue(0)
        self.spinBox_2.setValue(0)
        self.spinBox_3.setValue(0)

    def minute_plus(self):
        self.minutes += 1
        self.textBrowser.setText(f"{str(self.hours).zfill(2)}:{str(self.minutes).zfill(2)}:{str(self.seconds).zfill(2)}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
