number = 0

questions = [
                [number, "Which city is also known as the 'City of joy' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Kolkata"],
                [number, "Which city is also known as the 'City of dreams' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Mumbai"],
                [number, "Which city is also known as the 'Silicon Valley of India' ?", "Kolkata", "Mumbai", "Bangalore", "Delhi", "Bangalore"],
                [number, "Which city is also known as the 'Steel city of India' ?", "Kolkata", "Jamshedpur", "Chennai", "Delhi", "Jamshedpur"],
                [number, "Which city is also known as the 'Rome of the East' ?", "Kolkata", "Mumbai", "Chennai", "Mangalore", "Mangalore"],
                [number, "Which city is also known as the 'Land of knowledge' ?", "Nalanda", "Mumbai", "Chennai", "Delhi", "Nalanda"],
                [number, "Which city is also known as the 'Coal Capital of India' ?", "Kolkata", "Dhanbad", "Chennai", "Delhi", "Dhanbad"],
                [number, "Which city is also known as the 'Cashew Capital of the World' ?", "Kolkata", "Mumbai", "Kolam", "Delhi", "Kolam"],
                [number, "Which city is also known as the 'Oxford of the East' ?", "Kolkata", "Mumbai", "Pune", "Delhi", "Pune"],
                [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],

                [number, "How is the angular momentum of an electron calcuated ?", "(n*h)**2 / pi", "n*h / 2*pi", "n / 2*pi*h", "n*2*pi / h", "n*h / 2*pi"],
                [number, "Whose name is used in an operator in the Schrodinger's Quantum-Mechanical atomic model equation ?", "Bohr", "Seaborge", "Hamilton", "Schrodinger", "Hamilton"],
                # [number, "Which city is also known as the 'Silicon Valley of India' ?", "Kolkata", "Mumbai", "Bangalore", "Delhi", "Bangalore"],
                # [number, "Which city is also known as the 'Steel city of India' ?", "Kolkata", "Jamshedpur", "Chennai", "Delhi", "Jamshedpur"],
                # [number, "Which city is also known as the 'Rome of the East' ?", "Kolkata", "Mumbai", "Chennai", "Mangalore", "Mangalore"],
                # [number, "Which city is also known as the 'Land of knowledge' ?", "Nalanda", "Mumbai", "Chennai", "Delhi", "Nalanda"],
                # [number, "Which city is also known as the 'Coal Capital of India' ?", "Kolkata", "Dhanbad", "Chennai", "Delhi", "Dhanbad"],
                # [number, "Which city is also known as the 'Cashew Capital of the World' ?", "Kolkata", "Mumbai", "Kolam", "Delhi", "Kolam"],
                # [number, "Which city is also known as the 'Oxford of the East' ?", "Kolkata", "Mumbai", "Pune", "Delhi", "Pune"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],

                # [number, "Which city is also known as the 'City of joy' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Kolkata"],
                # [number, "Which city is also known as the 'City of dreams' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Mumbai"],
                # [number, "Which city is also known as the 'Silicon Valley of India' ?", "Kolkata", "Mumbai", "Bangalore", "Delhi", "Bangalore"],
                # [number, "Which city is also known as the 'Steel city of India' ?", "Kolkata", "Jamshedpur", "Chennai", "Delhi", "Jamshedpur"],
                # [number, "Which city is also known as the 'Rome of the East' ?", "Kolkata", "Mumbai", "Chennai", "Mangalore", "Mangalore"],
                # [number, "Which city is also known as the 'Land of knowledge' ?", "Nalanda", "Mumbai", "Chennai", "Delhi", "Nalanda"],
                # [number, "Which city is also known as the 'Coal Capital of India' ?", "Kolkata", "Dhanbad", "Chennai", "Delhi", "Dhanbad"],
                # [number, "Which city is also known as the 'Cashew Capital of the World' ?", "Kolkata", "Mumbai", "Kolam", "Delhi", "Kolam"],
                # [number, "Which city is also known as the 'Oxford of the East' ?", "Kolkata", "Mumbai", "Pune", "Delhi", "Pune"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],

                # [number, "Which city is also known as the 'City of joy' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Kolkata"],
                # [number, "Which city is also known as the 'City of dreams' ?", "Kolkata", "Mumbai", "Chennai", "Delhi", "Mumbai"],
                # [number, "Which city is also known as the 'Silicon Valley of India' ?", "Kolkata", "Mumbai", "Bangalore", "Delhi", "Bangalore"],
                # [number, "Which city is also known as the 'Steel city of India' ?", "Kolkata", "Jamshedpur", "Chennai", "Delhi", "Jamshedpur"],
                # [number, "Which city is also known as the 'Rome of the East' ?", "Kolkata", "Mumbai", "Chennai", "Mangalore", "Mangalore"],
                # [number, "Which city is also known as the 'Land of knowledge' ?", "Nalanda", "Mumbai", "Chennai", "Delhi", "Nalanda"],
                # [number, "Which city is also known as the 'Coal Capital of India' ?", "Kolkata", "Dhanbad", "Chennai", "Delhi", "Dhanbad"],
                # [number, "Which city is also known as the 'Cashew Capital of the World' ?", "Kolkata", "Mumbai", "Kolam", "Delhi", "Kolam"],
                # [number, "Which city is also known as the 'Oxford of the East' ?", "Kolkata", "Mumbai", "Pune", "Delhi", "Pune"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
                # [number, "Which city is also known as the 'Abode of the God' ?", "Kolkata", "Mumbai", "Prayagraj", "Delhi", "Prayagraj"],
            ]
