# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_004.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(609, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 591, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Banner")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(40, 120, 251, 131))
        self.listView.setObjectName("listView")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(50, 130, 231, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 160, 231, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(50, 190, 231, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(50, 220, 231, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.listView_2 = QtWidgets.QListView(self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(310, 120, 251, 131))
        self.listView_2.setObjectName("listView_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(320, 130, 231, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(320, 160, 231, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(320, 190, 231, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(320, 220, 231, 17))
        self.radioButton_8.setObjectName("radioButton_8")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 85, 431, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 181, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 270, 75, 21))
        self.pushButton.setObjectName("pushButton")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(20, 490, 581, 31))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 1, 251, 20))
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(self.frame_3)
        self.textEdit.setGeometry(QtCore.QRect(420, 0, 104, 21))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(370, 0, 41, 20))
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(540, 0, 31, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(20, 540, 581, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 561, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 39, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(510, 60, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(310, 349, 281, 121))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 30, 256, 81))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_13.setGeometry(QtCore.QRect(20, 40, 110, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_14.setGeometry(QtCore.QRect(140, 40, 110, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_15.setGeometry(QtCore.QRect(20, 80, 110, 20))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_16.setGeometry(QtCore.QRect(140, 80, 110, 20))
        self.radioButton_16.setObjectName("radioButton_16")
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(110, 10, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 320, 561, 20))
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 349, 281, 121))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 256, 81))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 40, 110, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_10.setGeometry(QtCore.QRect(140, 40, 110, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_11.setGeometry(QtCore.QRect(20, 80, 110, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_12.setGeometry(QtCore.QRect(140, 80, 110, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(100, 10, 47, 13))
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.confirm)
        self.pushButton_2.clicked.connect(self.OK)
        self.pushButton_3.clicked.connect(self.clearup)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VK Converters"))
        self.label.setText(_translate("MainWindow", "GUI  Conversion  Programme"))
        self.radioButton.setText(_translate("MainWindow", "Weight Conversion"))
        self.radioButton_2.setText(_translate("MainWindow", "Length Conversion"))
        self.radioButton_3.setText(_translate("MainWindow", "Area Conversion"))
        self.radioButton_4.setText(_translate("MainWindow", "Volume Conversion"))
        self.radioButton_5.setText(_translate("MainWindow", "Time Conversion"))
        self.radioButton_6.setText(_translate("MainWindow", "Temperature Conversion"))
        self.radioButton_7.setText(_translate("MainWindow", "Number Conversion"))
        self.radioButton_8.setText(_translate("MainWindow", "Speed Conversion"))
        self.label_2.setText(_translate("MainWindow", "Step 1  :  Select the conversion type from below ..."))
        self.label_3.setText(_translate("MainWindow", "... and then confirm it here ."))
        self.pushButton.setText(_translate("MainWindow", "Confirm"))
        self.label_5.setText(_translate("MainWindow", "Step 3  :  Enter the values and click the OK Button ."))
        self.label_6.setText(_translate("MainWindow", "Value : "))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.label_8.setText(_translate("MainWindow", "Step 4  :  Obtain the result here ."))
        self.pushButton_3.setText(_translate("MainWindow", "Reset"))
        self.radioButton_13.setText(_translate("MainWindow", "Value1"))
        self.radioButton_14.setText(_translate("MainWindow", "Value2"))
        self.radioButton_15.setText(_translate("MainWindow", "Value3"))
        self.radioButton_16.setText(_translate("MainWindow", "Value4"))
        self.label_10.setText(_translate("MainWindow", "To : "))
        self.label_4.setText(_translate("MainWindow", "Step 2  :  Select the unit you want to be converted from and converted to ."))
        self.radioButton_9.setText(_translate("MainWindow", "Value1"))
        self.radioButton_10.setText(_translate("MainWindow", "Value2"))
        self.radioButton_11.setText(_translate("MainWindow", "Value3"))
        self.radioButton_12.setText(_translate("MainWindow", "Value4"))
        self.label_7.setText(_translate("MainWindow", "From : "))

    def confirm(self):
        if self.radioButton.isChecked():
            list = ["gram","kilogram","pound","tonne"]

        elif self.radioButton_2.isChecked():
            list = ["centimetre","metre","kilometre","mile"]

        elif self.radioButton_3.isChecked():
            list = ["sq. metre","acre","hectare","sq. kilometre"]

        elif self.radioButton_4.isChecked():
            list = ["cubic mm (mm^3)","millilitre (ml)","cubic cm (litre)","cubic m (kilolitre)"]

        elif self.radioButton_5.isChecked():
            list = ["second","minute","hour","day"]

        elif self.radioButton_6.isChecked():
            list = ["celsius","farhenheit","kelvin","rankine"]

        elif self.radioButton_7.isChecked():
            list = ["decimal","binary","octal","hexadecimal"]

        elif self.radioButton_8.isChecked():
            list = ["m/sec","km/hr","mach","mile/hr"]

        self.radioButton_9.setText(list[0])
        self.radioButton_10.setText(list[1])
        self.radioButton_11.setText(list[2])
        self.radioButton_12.setText(list[3])

        self.radioButton_13.setText(list[0])
        self.radioButton_14.setText(list[1])
        self.radioButton_15.setText(list[2])
        self.radioButton_16.setText(list[3])

    def OK(self):
        value = float(self.textEdit.toPlainText())

        if self.radioButton.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # gram to kilogram
                    answer = value/1000 ; unit = "kilogram"
                elif self.radioButton_15.isChecked(): # gram to pound
                    answer = value*2.2/1000 ; unit = "pound"
                elif self.radioButton_16.isChecked(): # gram to ton
                    answer = value/100000 ; unit = "ton"

                from_value = "gram"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # kilogram to gram
                    answer = value*1000 ; unit = "gram"
                elif self.radioButton_15.isChecked(): # kilogram to pound
                    answer = value*2.2 ; unit = "pound"
                elif self.radioButton_16.isChecked(): # kilogram to ton
                    answer = value/1000 ; unit = "ton"

                from_value = "kilogram"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # pound to gram
                    answer = value*450 ; unit = "gram"
                elif self.radioButton_14.isChecked(): # pound to kilogram
                    answer = value*0.45 ; unit = "kilogram"
                elif self.radioButton_16.isChecked(): # pound to ton
                    answer = value*0.0045 ; unit = "ton"

                from_value = "pound"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # ton to gram
                    answer = value*100000 ; unit = "gram"
                elif self.radioButton_14.isChecked(): # ton to kilogram
                    answer = value*100 ; unit = "kilogram"
                elif self.radioButton_15.isChecked(): # ton to pound
                    answer = value*2205 ; unit = "pound"

                from_value = "tonne"

        elif self.radioButton_2.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # centimetre to metre
                    answer = value/100 ; unit = "metre"
                elif self.radioButton_15.isChecked(): # centimetre to kilometre
                    answer = value/100000 ; unit = "kilometre"
                elif self.radioButton_16.isChecked(): # centimetre to mile
                    answer = value/160000 ; unit = "mile"

                from_value = "centimetre"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # metre to centimetre
                    answer = value*100 ; unit = "centimetre"
                elif self.radioButton_15.isChecked(): # metre to kilometre
                    answer = value/1000 ; unit = "kilometre"
                elif self.radioButton_16.isChecked(): # metre to mile
                    answer = value/1600 ; unit = "mile"

                from_value = "metre"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # kilometre to centimetre
                    answer = value*100000 ; unit = "centimetre"
                elif self.radioButton_14.isChecked(): # kilometre to metre
                    answer = value*1000 ; unit = "metre"
                elif self.radioButton_16.isChecked(): # kilometre to mile
                    answer = value*0.625 ; unit = "mile"

                from_value = "kilometre"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # mile to centimetre
                    answer = value*160000 ; unit = "centimetre"
                elif self.radioButton_14.isChecked(): # mile to metre
                    answer = value*1600 ; unit = "metre"
                elif self.radioButton_15.isChecked(): # mile to kilometre
                    answer = value*1.6 ; unit = "kilometre"

                from_value = "mile"

        elif self.radioButton_3.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # sq. metre to acre
                    answer = value/4000 ; unit = "acre"
                elif self.radioButton_15.isChecked(): # sq. metre to hectare 
                    answer = value/10000 ; unit = "hectare"
                elif self.radioButton_16.isChecked(): # sq. metre to sq. kilometre
                    answer = value/1000000 ; unit = "sq. km"

                from_value = "sq. m"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # acre to sq. metre
                    answer = value*4000 ; unit = "sq. m"
                elif self.radioButton_15.isChecked(): # acre to hectare
                    answer = value*0.4 ; unit = "hectare"
                elif self.radioButton_16.isChecked(): # acre to sq. kilometre
                    answer = value/250 ; unit = "sq. km"

                from_value = "acre"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # hectare to sq. metre
                    answer = value*10000 ; unit = "sq. m"
                elif self.radioButton_14.isChecked(): # hectare to acre
                    answer = value*2.5 ; unit = "acre"
                elif self.radioButton_16.isChecked(): # hectare to sq. kilometre
                    answer = value/100 ; unit = "sq. km"

                from_value = "hectare"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # sq. kilometre to sq. metre
                    answer = value*1000000 ; unit = "sq. m"
                elif self.radioButton_14.isChecked(): # sq. kilometre to acre
                    answer = value*250 ; unit = "acre"
                elif self.radioButton_15.isChecked(): # sq. kilometre to hectare
                    answer = value*100 ; unit = "hectare"

                from_value = "sq. km"

        elif self.radioButton_4.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # cubic mm to milli-litre
                    answer = value ; unit = "ml"
                elif self.radioButton_15.isChecked(): # cubic mm to litre
                    answer = value ; unit = "l"
                elif self.radioButton_16.isChecked(): # cubic mm to kilo-litre
                    answer = value ; unit = "kl"

                from_value = "cubic mm"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # milli-litre to cubic mm
                    answer = value ; unit = "cubic mm"
                elif self.radioButton_15.isChecked(): # milli-litre to litre
                    answer = value ; unit = "l"
                elif self.radioButton_16.isChecked(): # milli-litre to kilo-litre
                    answer = value ; unit = "kl"

                from_value = "millilitre"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # litre to cubic mm
                    answer = value ; unit = "cubic mm"
                elif self.radioButton_14.isChecked(): # litre to milli-litre
                    answer = value ; unit = "ml"
                elif self.radioButton_16.isChecked(): # litre to kilo-litre
                    answer = value ; unit = "kl"

                from_value = "litre"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # kilo-litre to cubic mm
                    answer = value ; unit = "cubic mm"
                elif self.radioButton_14.isChecked(): # kilo-litre to milli-litre
                    answer = value ; unit = "ml"
                elif self.radioButton_15.isChecked(): # kilo-litre to litre
                    answer = value ; unit = "l"

                from_value = "kilolitre"

        elif self.radioButton_5.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # second to minute
                    answer = value/60 ; unit = "minute"
                elif self.radioButton_15.isChecked(): # second to hour
                    answer = value/3600 ; unit = "hour"
                elif self.radioButton_16.isChecked(): # second to day
                    answer = value/86400 ; unit = "day"

                from_value = "second"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # minute to second
                    answer = value*60 ; unit = "second"
                elif self.radioButton_15.isChecked(): # minute to hour
                    answer = value/60 ; unit = "hour"
                elif self.radioButton_16.isChecked(): # minute to day
                    answer = value/1440 ; unit = "day"

                from_value = "minute"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # hour to second
                    answer = value*3600 ; unit = "second"
                elif self.radioButton_14.isChecked(): # hour to minute
                    answer = value*60 ; unit = "minute"
                elif self.radioButton_16.isChecked(): # hour to day
                    answer = value/24 ; unit = "day"

                from_value = "hour"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # day to second
                    answer = value*86400 ; unit = "second"
                elif self.radioButton_14.isChecked(): # day to minute
                    answer = value*1440 ; unit = "minute"
                elif self.radioButton_15.isChecked(): # day to hour
                    answer = value*24 ; unit = "hour"

                from_value = "day"

        elif self.radioButton_6.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # celsius to farhenheit
                    answer = (value*1.8)+32 ; unit = "F"
                elif self.radioButton_15.isChecked(): # celsius to kelvin
                    answer = value+273.15 ; unit = "K"
                elif self.radioButton_16.isChecked(): # celsius to rankine
                    answer = (value+273.15)*1.8 ; unit = "R"

                from_value = "C"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # farhenheit to celsius
                    answer = (value-32)/1.8 ; unit = "C"
                elif self.radioButton_15.isChecked(): # farhenheit to kelvin
                    answer = (value+459.67)/1.8 ; unit = "K"
                elif self.radioButton_16.isChecked(): # farhenheit to rankine
                    answer = value+459.67 ; unit = "R"

                from_value = "F"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # kelvin to celsius
                    answer = value-273.15 ; unit = "C"
                elif self.radioButton_14.isChecked(): # kelvin to farhenheit
                    answer = (value*1.8)-459.67 ; unit = "F"
                elif self.radioButton_16.isChecked(): # kelvin to rankine
                    answer = value*1.8 ; unit = "R"

                from_value = "K"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # rankine to celsius
                    answer = (value-491.67)/1.8 ; unit = "C"
                elif self.radioButton_14.isChecked(): # rankine to farhenheit
                    answer = value-459.67 ; unit = "F"
                elif self.radioButton_15.isChecked(): # rankine to kelvin
                    answer = value/1.8 ; unit = "K"

                from_value = "R"

        elif self.radioButton_7.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # decimal to binary
                    answer = bin(int(value)) ; unit = "binary"
                elif self.radioButton_15.isChecked(): # decimal to octal
                    answer = oct(int(value)) ; unit = "octal"
                elif self.radioButton_16.isChecked(): # decimal to hexadecimal
                    answer = hex(int(value)) ; unit = "hexadecimal"

                from_value = "decimal"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # binary to decimal
                    answer = int(value) ; unit = "decimal"
                elif self.radioButton_15.isChecked(): # binary to octal
                    answer = oct(int(value)) ; unit = "octal"
                elif self.radioButton_16.isChecked(): # binary to hexadecimal
                    answer = hex(int(value)) ; unit = "hexadecimal"

                from_value = "binary"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # octal to decimal
                    answer = int(value) ; unit = "decimal"
                elif self.radioButton_14.isChecked(): # octal to binary
                    answer = bin(int(value)) ; unit = "binary"
                elif self.radioButton_16.isChecked(): # octal to hexadecimal
                    answer = hex(int(value)) ; unit = "hexadecimal"

                from_value = "octal"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # hexadecimal to decimal
                    answer = int(value) ; unit = "decimal"
                elif self.radioButton_14.isChecked(): # hexadecimal to binary
                    answer = bin(int(value)) ; unit = "binary"
                elif self.radioButton_15.isChecked(): # hexadecimal to octal
                    answer = oct(int(value)) ; unit = "octal"

                from_value = "hexadecimal"

        elif self.radioButton_8.isChecked():
            if self.radioButton_9.isChecked():
                if self.radioButton_14.isChecked(): # m/sec to km/hr
                    answer = value*3.6 ; unit = "km/hr"
                elif self.radioButton_15.isChecked(): # m/sec to mach
                    answer = value*0.003 ; unit = "mach"
                elif self.radioButton_16.isChecked(): # m/sec to mile/hr
                    answer = value*2.24 ; unit = "mph"

                from_value = "m/sec"
                
            if self.radioButton_10.isChecked():
                if self.radioButton_13.isChecked(): # km/hr to m/sec
                    answer = value*0.27 ; unit = "m/sec"
                elif self.radioButton_15.isChecked(): # km/hr to mach
                    answer = value*0.0008 ; unit = "mach"
                elif self.radioButton_16.isChecked(): # km/hr to mile/hr
                    answer = value*0.625 ; unit = "mph"

                from_value = "km/hr"

            if self.radioButton_11.isChecked():
                if self.radioButton_13.isChecked(): # mach to m/sec
                    answer = value*340 ; unit = "m/sec"
                elif self.radioButton_14.isChecked(): # mach to km/hr
                    answer = value*1225 ; unit = "km/hr"
                elif self.radioButton_16.isChecked(): # mach to mile/hr
                    answer = value*761 ; unit = "mph"

                from_value = "mach"

            if self.radioButton_12.isChecked():
                if self.radioButton_13.isChecked(): # mile/hr to m/sec
                    answer = value*0.44 ; unit = "m/sec"
                elif self.radioButton_14.isChecked(): # mile/hr to km/hr
                    answer = value*1.6 ; unit = "km/hr"
                elif self.radioButton_15.isChecked(): # mile/hr to mach
                    answer = value*0.001 ; unit = "mach"

                from_value = "mile/hr"

            
        self.label_9.setText(f"{value} {from_value} = {answer} {unit} . ")

        with open("Calculator_History.txt","a+") as file:
            file.write(f"{value} {from_value} = {answer} {unit} .\n")
    
    def clearup(self):
        self.textEdit.setText("0")

        self.radioButton_9.setText("Value1")
        self.radioButton_10.setText("Value2")
        self.radioButton_11.setText("Value3")
        self.radioButton_12.setText("Value4")
        self.radioButton_13.setText("Value1")
        self.radioButton_14.setText("Value2")
        self.radioButton_15.setText("Value3")
        self.radioButton_16.setText("Value4")

        self.radioButton.setChecked(False)
        self.radioButton_2.setChecked(False)
        self.radioButton_3.setChecked(False)
        self.radioButton_4.setChecked(False)
        self.radioButton_5.setChecked(False)
        self.radioButton_6.setChecked(False)
        self.radioButton_7.setChecked(False)
        self.radioButton_8.setChecked(False)
 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
