# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Translator(1).ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import googletrans
# from Translator_History_by_VK import Ui_Dialog as history_window
import Translator_Settings_by_VK as TSbV
# from About_by_VK import Ui_Dialog as about_window
# from Help_by_VK import Ui_Dialog as history_window


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setFixedSize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(220, 210, 69, 31))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Old English Text MT")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_2.setGeometry(QtCore.QRect(630, 400, 75, 23))
        self.pushbutton_2.setObjectName("pushbutton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 290, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 480, 761, 80))
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 210, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(600, 210, 69, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushbutton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_1.setGeometry(QtCore.QRect(630, 340, 75, 21))
        self.pushbutton_1.setObjectName("pushbutton_1")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 340, 491, 81))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuHistory = QtWidgets.QMenu(self.menubar)
        self.menuHistory.setObjectName("menuHistory")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        default_lang_1 = "English"
        default_lang_2 = "Hindi"

        for x in googletrans.LANGUAGES.values():
            self.comboBox.addItem(x.capitalize())
            self.comboBox_2.addItem(x.capitalize())

        self.comboBox.setCurrentText(default_lang_1)
        self.comboBox_2.setCurrentText(default_lang_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushbutton_1.clicked.connect(self.clear)
        self.pushbutton_2.clicked.connect(self.translate)

        # self.menuHistory.aboutToShow.connect(self.history_page)
        self.menuSettings.aboutToShow.connect(self.settings_page)
        # self.menuAbout.aboutToShow.connect(self.about_page)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Translator - by VK"))
        self.label_2.setText(_translate("MainWindow", "Convert the given word / phrase / sentence :"))
        self.label.setText(_translate("MainWindow", "Translator"))
        self.pushbutton_2.setText(_translate("MainWindow", "Translate"))
        self.label_4.setText(_translate("MainWindow", "Enter the word / phrase / sentence you want to convert to :"))
        self.label_5.setText(_translate("MainWindow", "To :"))
        self.label_6.setText(_translate("MainWindow", "Translated Text :"))
        self.pushbutton_1.setText(_translate("MainWindow", "Clear"))
        self.label_3.setText(_translate("MainWindow", "From :"))
        self.menuHistory.setTitle(_translate("MainWindow", "History"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))

    def clear(self):
        self.textEdit.clear()
        self.textBrowser.clear()

    def translate(self):
        rawdata1 = self.comboBox.currentText().lower()
        rawdata2 = self.comboBox_2.currentText().lower()
        translate_whom = self.textEdit.toPlainText()

        key = list(googletrans.LANGUAGES.keys())
        value = list(googletrans.LANGUAGES.values())

        location1 = value.index(rawdata1)
        location2 = value.index(rawdata2)

        translate_from = key[location1]
        translate_to = key[location2]

        translator = googletrans.Translator()
        result = translator.translate(translate_whom, src=translate_from, dest=translate_to)

        result_text = result.text
        self.textBrowser.setText(result_text)
         
        with open("Translator_History_by_VK.txt", "a", encoding="utf-8") as writer:
            info = f"# {translate_whom} (English) : (Hindi) {result_text}"
            writer.write(info)
            writer.write("\n\n")

    # def history_page(self):
    #     dialog = QtWidgets.QDialog()
    #     dialog.ui = history_window()
    #     dialog.ui.setupUi(dialog)
    #     dialog.exec_()
    #     dialog.show()

    def settings_page(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = TSbV.Ui_Dialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    # def about_page(self):
    #     dialog = QtWidgets.QDialog()
    #     dialog.ui = about_window()
    #     dialog.ui.setupUi(dialog)
    #     dialog.exec_()
    #     dialog.show()

    def help_page(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
